-- Z-Health AI Database Schema
-- Run this in your Supabase SQL Editor (supabase.com > project > SQL Editor)
-- This creates all tables needed for the application.

-- ============================================================
-- Conversations
-- Stores chat conversation metadata. Each conversation belongs
-- to a user and optionally targets a specific workspace/page.
-- ============================================================
create table conversations (
  id uuid default gen_random_uuid() primary key,
  user_id text not null,
  user_email text,
  title text not null default 'New conversation',
  workspace text not null default 'all',
  page_context_id integer,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- ============================================================
-- Messages
-- Individual messages within a conversation. Cascade-deletes
-- when the parent conversation is removed.
-- ============================================================
create table messages (
  id uuid default gen_random_uuid() primary key,
  conversation_id uuid references conversations(id) on delete cascade,
  role text not null check (role in ('user', 'assistant', 'system')),
  content text not null default '',
  files jsonb,
  pending_action jsonb,
  action_result jsonb,
  report_data jsonb,
  created_at timestamptz default now()
);
create index idx_messages_conversation on messages(conversation_id);

-- ============================================================
-- User Preferences
-- Per-user settings (model, theme, workspace, sidebar state).
-- ============================================================
create table user_preferences (
  id uuid default gen_random_uuid() primary key,
  user_id text unique not null,
  user_email text,
  selected_model text default 'gemini-2.0-flash',
  workspace text default 'all',
  theme text default 'light',
  sidebar_collapsed boolean default false,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- ============================================================
-- Activity Log
-- Tracks user actions across workspaces for auditing /
-- analytics purposes.
-- ============================================================
create table activity_log (
  id uuid default gen_random_uuid() primary key,
  user_id text not null,
  user_email text,
  action_type text not null,
  workspace text,
  target_type text,
  target_id text,
  details jsonb,
  created_at timestamptz default now()
);
create index idx_activity_workspace on activity_log(workspace);
create index idx_activity_user on activity_log(user_id);

-- ============================================================
-- Saved Reports
-- Reports generated by the AI that users choose to save for
-- later reference.
-- ============================================================
create table saved_reports (
  id uuid default gen_random_uuid() primary key,
  user_id text not null,
  title text not null,
  report_type text not null,
  report_data jsonb not null,
  workspace text,
  created_at timestamptz default now()
);

-- ============================================================
-- API Cache
-- Caches external API responses (WordPress, Keap, Thinkific,
-- GA4) to reduce redundant calls and speed up page loads.
-- ============================================================
create table if not exists api_cache (
  cache_key text primary key,
  data jsonb not null,
  expires_at timestamptz not null,
  updated_at timestamptz default now()
);
create index if not exists idx_api_cache_expires on api_cache(expires_at);
